# ========================================
# Find and Install MSIX Certificate Automatically
# ========================================
# This script searches for .cer files generated by electron-builder
# and automatically installs them to Trusted Root CA
# Run this script as Administrator

param(
    [string]$SearchDir = "dist-electron"
)

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Find and Install MSIX Certificate" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if running as Administrator
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host "[ERROR] This script must be run as Administrator!" -ForegroundColor Red
    Write-Host "Right-click PowerShell and select 'Run as Administrator'" -ForegroundColor Yellow
    exit 1
}

# Get project root
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir

# Search for .cer files
$SearchPaths = @(
    Join-Path $ProjectRoot $SearchDir,
    Join-Path $ProjectRoot "certificates",
    Join-Path $ProjectRoot "dist"
)

Write-Host "[1/3] Searching for certificate files..." -ForegroundColor Yellow

$certFiles = @()
foreach ($path in $SearchPaths) {
    if (Test-Path $path) {
        $found = Get-ChildItem -Path $path -Filter "*.cer" -Recurse -ErrorAction SilentlyContinue
        if ($found) {
            $certFiles += $found
        }
    }
}

if ($certFiles.Count -eq 0) {
    Write-Host "[ERROR] No .cer certificate files found!" -ForegroundColor Red
    Write-Host ""
    Write-Host "Searched in:" -ForegroundColor Yellow
    foreach ($path in $SearchPaths) {
        Write-Host "  - $path" -ForegroundColor Gray
    }
    Write-Host ""
    Write-Host "Please either:" -ForegroundColor Yellow
    Write-Host "  1. Build your MSIX package first (electron-builder will generate a .cer file)" -ForegroundColor White
    Write-Host "  2. Or run: scripts\generate-certificate.ps1" -ForegroundColor White
    exit 1
}

Write-Host "[INFO] Found $($certFiles.Count) certificate file(s):" -ForegroundColor Green
foreach ($cert in $certFiles) {
    Write-Host "  - $($cert.FullName)" -ForegroundColor Gray
}

# Use the first certificate found (or let user choose)
$CertPath = $certFiles[0].FullName
if ($certFiles.Count -gt 1) {
    Write-Host ""
    Write-Host "Multiple certificates found. Using the first one:" -ForegroundColor Yellow
    Write-Host "  $CertPath" -ForegroundColor Gray
    Write-Host ""
    $confirm = Read-Host "Continue with this certificate? (Y/N)"
    if ($confirm -ne "Y" -and $confirm -ne "y") {
        Write-Host "Cancelled." -ForegroundColor Yellow
        exit 0
    }
}

Write-Host ""
Write-Host "[2/3] Installing certificate to Trusted Root CA..." -ForegroundColor Yellow

try {
    $cert = Import-Certificate `
        -FilePath $CertPath `
        -CertStoreLocation "Cert:\LocalMachine\Root"
    
    if ($null -eq $cert) {
        Write-Host "[ERROR] Failed to import certificate" -ForegroundColor Red
        exit 1
    }
    
    Write-Host "[SUCCESS] Certificate installed successfully!" -ForegroundColor Green
    Write-Host "  Thumbprint: $($cert.Thumbprint)" -ForegroundColor Gray
    Write-Host "  Subject: $($cert.Subject)" -ForegroundColor Gray
    
} catch {
    Write-Host "[ERROR] Failed to install certificate: $_" -ForegroundColor Red
    Write-Host ""
    Write-Host "Common issues:" -ForegroundColor Yellow
    Write-Host "  - Certificate already installed (this is OK)" -ForegroundColor Gray
    Write-Host "  - Insufficient permissions (run as Administrator)" -ForegroundColor Gray
    exit 1
}

Write-Host ""
Write-Host "[3/3] Verifying installation..." -ForegroundColor Yellow

$installedCert = Get-ChildItem -Path "Cert:\LocalMachine\Root" | Where-Object { $_.Thumbprint -eq $cert.Thumbprint }
if ($null -ne $installedCert) {
    Write-Host "[SUCCESS] Certificate verified in Trusted Root CA store!" -ForegroundColor Green
} else {
    Write-Host "[WARNING] Certificate may not be properly installed" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "✅ Certificate installation complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "You can now install your MSIX package without errors." -ForegroundColor Green
Write-Host ""

